spring:
  application:
    name: auth-service

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

  autoconfigure:
    exclude:
      - net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration

server:
  port: 4000