spring:
  application:
    name: order-service




server:
  port: 4004

product:
  service:
    address: localhost
    grpc:
      port: 8002

user:
  service:
    address: localhost
    grpc:
      port: 8003

billing:
  service:
    address: localhost
    grpc:
      port: 8001